Repository ASFHyP3/hyp3-flood-monitoring, pull requests merged in 2023-06, with the labels that each got.

#44 change the prefix structure of the product
  CHANGELOG.md
  tests/test_transfer_products.py
  transfer-products/src/transfer_products.py
Labels: patch

#43 Update hyp3 url and bucket name for production deployment
  .github/workflows/deploy-prod.yml
Labels: bumpless

#46 Release v0.3.0
  .github/actions/deploy/action.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-test.yml
  CHANGELOG.md
  README.md
  cloudformation.yml
  tests/test_transfer_products.py
  transfer-products/cloudformation.yml
  transfer-products/src/transfer_products.py
Labels: minor

#48 Release v0.3.1
  .github/workflows/changelog.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release.yml
  CHANGELOG.md
  transfer-products/cloudformation.yml
Labels: patch

#49 Copy objects directly to target bucket
  .github/workflows/deploy-test.yml
  CHANGELOG.md
  tests/test_transfer_products.py
  transfer-products/src/transfer_products.py
Labels: minor

#50 grant s3:GetObject permissions for transfer-products lambda
  transfer-products/cloudformation.yml
Labels: bumpless

#51 don't copy s3 tags in transfer-products
  transfer-products/src/transfer_products.py
Labels: bumpless

#52 Release 0.4.0
  .github/workflows/deploy-test.yml
  CHANGELOG.md
  tests/test_transfer_products.py
  transfer-products/cloudformation.yml
  transfer-products/src/transfer_products.py
Labels: minor

#54 Release v0.4.1
  CHANGELOG.md
  transfer-products/cloudformation.yml
  transfer-products/src/transfer_products.py
Labels: patch
